"""assistance_preparation

Revision ID: 20260929054644
Revises: 20260924000000
Create Date: 2026-09-29 05:46:45.732964

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20260929054644"
down_revision: Union[str, Sequence[str], None] = "20260924000000"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assistance_preparations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identity", sa.String(length=64), nullable=False),
        sa.Column("rater_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("session_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("method_name", sa.String(length=64), nullable=False),
        sa.Column("spec_json", sa.Text(), nullable=False),
        sa.Column("params_json", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("demanded", sa.Boolean(), nullable=False),
        sa.Column("artifact_json", sa.Text(), nullable=True),
        sa.Column("owner_token", sa.String(length=32), nullable=True),
        sa.Column("claim_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["rater_id"], ["raters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identity", name="uq_preparation_identity"),
    )
    op.create_index(
        op.f("ix_assistance_preparations_rater_id"),
        "assistance_preparations",
        ["rater_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assistance_preparations_status"),
        "assistance_preparations",
        ["status"],
        unique=False,
    )
    # A trigger also covers reset cascades and cancellation by other processes.
    # PostgreSQL delivers notifications only after the transaction commits.
    op.execute("""
        CREATE FUNCTION notify_assistance_preparation() RETURNS trigger AS $$
        BEGIN
            IF TG_OP = 'DELETE' THEN
                PERFORM pg_notify('assistance_preparation', OLD.id::text || ':' || 'deleted');
            ELSIF TG_OP = 'INSERT' OR NEW.status IS DISTINCT FROM OLD.status
                  OR NEW.demanded IS DISTINCT FROM OLD.demanded THEN
                PERFORM pg_notify('assistance_preparation', NEW.id::text || ':' || NEW.status);
            END IF;
            RETURN NULL;
        END;
        $$ LANGUAGE plpgsql
    """)
    op.execute("""
        CREATE TRIGGER assistance_preparation_changed
        AFTER INSERT OR UPDATE OR DELETE ON assistance_preparations
        FOR EACH ROW EXECUTE FUNCTION notify_assistance_preparation()
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_assistance_preparations_status"), table_name="assistance_preparations")
    op.drop_index(op.f("ix_assistance_preparations_rater_id"), table_name="assistance_preparations")
    op.drop_table("assistance_preparations")
    op.execute("DROP FUNCTION notify_assistance_preparation()")
    # ### end Alembic commands ###
