"""assistance_turn_claim

Revision ID: 20260929072607
Revises: 20260929055545
Create Date: 2026-09-29 07:26:08.740501

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20260929072607"
down_revision: Union[str, Sequence[str], None] = "20260929055545"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assistance_sessions",
        sa.Column("revision", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.add_column(
        "assistance_sessions", sa.Column("advance_token", sa.String(length=32), nullable=True)
    )
    op.add_column(
        "assistance_sessions",
        sa.Column("advance_expires_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assistance_sessions", "advance_expires_at")
    op.drop_column("assistance_sessions", "advance_token")
    op.drop_column("assistance_sessions", "revision")
    # ### end Alembic commands ###
