"""assignment_activation

Revision ID: 20260929055545
Revises: 20260929054644
Create Date: 2026-09-29 05:55:46.257475

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20260929055545"
down_revision: Union[str, Sequence[str], None] = "20260929054644"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assistance_preparations", sa.Column("assignment_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "assistance_preparations", sa.Column("assignment_generation", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        "fk_preparation_assignment",
        "assistance_preparations",
        "question_assignments",
        ["assignment_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "question_assignments",
        sa.Column("generation", sa.Integer(), server_default=sa.text("1"), nullable=False),
    )
    op.add_column(
        "question_assignments", sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True)
    )
    # Previously served reservations were already visible to the participant.
    op.execute("UPDATE question_assignments SET activated_at = assigned_at")
    op.add_column(
        "raters",
        sa.Column("queue_revision", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.add_column(
        "raters",
        sa.Column("queue_mode", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("raters", "queue_mode")
    op.drop_column("raters", "queue_revision")
    op.drop_column("question_assignments", "activated_at")
    op.drop_column("question_assignments", "generation")
    op.drop_constraint("fk_preparation_assignment", "assistance_preparations", type_="foreignkey")
    op.drop_column("assistance_preparations", "assignment_generation")
    op.drop_column("assistance_preparations", "assignment_id")
    # ### end Alembic commands ###
